server:
  port: 8101
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8102/eureka/
management:
  endpoints:
    health:
      enabled: true
      show-details: always
    web:
      exposure:
        include: "*"
spring:
  redis:
    host: 192.168.0.100
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/AR_DB?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hinernate:
        hdm2dll:
          auto: update
    show-sql: true
security:
  oauth2:
    client:
      client-id: all_reviews
      client-secret: all_reviews_secret
    resource:
      jwt:
        key-value: all_reviews
oauth:
  grant-type: password
