server:
  port: 8200

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8102/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AR_DB?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    #initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
